services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Adjust based on your backend's port
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Adjust based on your frontend's port
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true  # Fixes issues with file watching
